### ISSUE TITLE
Look into automatic dependencies for Python in automake

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#305] opened 2020-02-06 17:23 UTC
We currently have increasingly many manual (and missing!) dependencies on Python files in the build system. Shurely we can do this automagically, as for C?

**Comment by rrthomas** [comment] 2020-02-10 16:17
Apparently not. The problem is C files depending on Python files. Inside a Python program there's no problem because it's compiled when it's run. So I guess this is a rather unusual situation. automake byte-compiles Python only at install time, so it doesn't need dependency information when running `make`.

Since much of this problem will go away when the specializer becomes a separate program, close the issue. We can keep adding dependencies manually for now.

**Closed as completed by rrthomas** 2020-02-10 16:17 UTC
