### ISSUE TITLE
Travis doesn't run building pForth in src test

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#253] opened 2019-08-01 16:29 UTC

**Comment by rrthomas** [comment] 2019-08-02 13:58
I can't reproduce this: as far as I can see, pForth is built in compatible Mit builds (i.e. `ENDISM=0`, `WORD_BYTES=4` at present). See e.g. https://travis-ci.org/rrthomas/mit/jobs/566961954

Closing.

**Closed as completed by rrthomas** 2019-08-02 13:58 UTC
